export const provinces = [
  { code: '01', name: 'Hà Nội' },
  { code: '02', name: 'Hà Giang' },
  { code: '04', name: 'Cao Bằng' },
  { code: '06', name: 'Bắc Kạn' },
  { code: '08', name: 'Tuyên Quang' },
  { code: '10', name: 'Lào Cai' },
  { code: '11', name: 'Điện Biên' },
  { code: '12', name: 'Lai Châu' },
  { code: '14', name: 'Sơn La' },
  { code: '15', name: 'Yên Bái' },
  { code: '17', name: 'Hoà Bình' },
  { code: '19', name: 'Thái Nguyên' },
  { code: '20', name: 'Lạng Sơn' },
  { code: '22', name: 'Quảng Ninh' },
  { code: '24', name: 'Bắc Giang' },
  { code: '25', name: 'Phú Thọ' },
  { code: '26', name: 'Vĩnh Phúc' },
  { code: '27', name: 'Bắc Ninh' },
  { code: '30', name: 'Hải Dương' },
  { code: '31', name: 'Hải Phòng' },
  { code: '33', name: 'Hưng Yên' },
  { code: '34', name: 'Thái Bình' },
  { code: '35', name: 'Hà Nam' },
  { code: '36', name: 'Nam Định' },
  { code: '37', name: 'Ninh Bình' },
  { code: '38', name: 'Thanh Hóa' },
  { code: '40', name: 'Nghệ An' },
  { code: '42', name: 'Hà Tĩnh' },
  { code: '44', name: 'Quảng Bình' },
  { code: '45', name: 'Quảng Trị' },
  { code: '46', name: 'Thừa Thiên Huế' },
  { code: '48', name: 'Đà Nẵng' },
  { code: '49', name: 'Quảng Nam' },
  { code: '51', name: 'Quảng Ngãi' },
  { code: '52', name: 'Bình Định' },
  { code: '54', name: 'Phú Yên' },
  { code: '56', name: 'Khánh Hòa' },
  { code: '58', name: 'Ninh Thuận' },
  { code: '60', name: 'Bình Thuận' },
  { code: '62', name: 'Kon Tum' },
  { code: '64', name: 'Gia Lai' },
  { code: '66', name: 'Đắk Lắk' },
  { code: '67', name: 'Đắk Nông' },
  { code: '68', name: 'Lâm Đồng' },
  { code: '70', name: 'Bình Phước' },
  { code: '72', name: 'Tây Ninh' },
  { code: '74', name: 'Bình Dương' },
  { code: '75', name: 'Đồng Nai' },
  { code: '77', name: 'Bà Rịa - Vũng Tàu' },
  { code: '79', name: 'Hồ Chí Minh' },
  { code: '80', name: 'Long An' },
  { code: '82', name: 'Tiền Giang' },
  { code: '83', name: 'Bến Tre' },
  { code: '84', name: 'Trà Vinh' },
  { code: '86', name: 'Vĩnh Long' },
  { code: '87', name: 'Đồng Tháp' },
  { code: '89', name: 'An Giang' },
  { code: '91', name: 'Kiên Giang' },
  { code: '92', name: 'Cần Thơ' },
  { code: '93', name: 'Hậu Giang' },
  { code: '94', name: 'Sóc Trăng' },
  { code: '95', name: 'Bạc Liêu' },
  { code: '96', name: 'Cà Mau' }
];

export const districts = [
  { code: '001', name: 'Ba Đình', province: 'Hà Nội' },
  { code: '002', name: 'Hoàn Kiếm', province: 'Hà Nội' },
  { code: '760', name: 'Quận 1', province: 'Hồ Chí Minh' },
  { code: '770', name: 'Quận 3', province: 'Hồ Chí Minh' },
  { code: '490', name: 'Hải Châu', province: 'Đà Nẵng' },
  { code: '511', name: 'TP. Vũng Tàu', province: 'Bà Rịa - Vũng Tàu' },
  { code: '024', name: 'TP. Hà Giang', province: 'Hà Giang' },
  { code: '040', name: 'TP. Cao Bằng', province: 'Cao Bằng' },
  { code: '058', name: 'TP. Bắc Kạn', province: 'Bắc Kạn' },
  { code: '070', name: 'TP. Tuyên Quang', province: 'Tuyên Quang' },
  // ... các quận/huyện mẫu khác
];

export const wards = [
  { code: '00001', name: 'Phúc Xá', district: 'Ba Đình' },
  { code: '00004', name: 'Trúc Bạch', district: 'Ba Đình' },
  { code: '02677', name: 'Bến Nghé', district: 'Quận 1' },
  { code: '02680', name: 'Bến Thành', district: 'Quận 1' },
  { code: '02701', name: 'Phường 6', district: 'Quận 3' },
  { code: '01861', name: 'Hải Châu I', district: 'Hải Châu' },
  { code: '02047', name: 'Phường 1', district: 'TP. Vũng Tàu' },
  { code: '00601', name: 'Ngọc Đường', district: 'TP. Hà Giang' },
  { code: '00801', name: 'Hợp Giang', district: 'TP. Cao Bằng' },
  { code: '01001', name: 'Phùng Chí Kiên', district: 'TP. Bắc Kạn' },
  { code: '01201', name: 'Tân Quang', district: 'TP. Tuyên Quang' },
  // ... các phường xã mẫu khác
];
